[package]
name = "new-krs-theme-choose"
version = "0.1.0"
authors = ["Kushashwa Ravi Shrimali <kushashwaravishrimali@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = "0.6"
itertools = "0.10.5"
